Feature/uno 102
UNO-Academy/UNO pull request #16
Opened 2022-11-07 11:21 UTC by Fercomp

<img width="358" alt="Captura de Tela 2022-11-07 às 08 15 01" src="https://user-images.githubusercontent.com/67404248/200298119-3d0e9ca2-c8a8-4b4a-91ce-87def6acdfad.png">

2022-11-08 12:25 UTC, LuisNascimento11 requested changes

2022-11-08 12:25 UTC, LuisNascimento11 commented on WhyNot/WhyNot/PeopleImagesData.swift
> +    @ViewBuilder func getPeopleImageView(image: UIImage, imageIndex: Int, totalImageNumber: Int) -> some View {
nome da função está muito grande

2022-11-08 12:25 UTC, LuisNascimento11 commented on WhyNot/WhyNot/PeopleImagesData.swift
> +            AnyView(Image(uiImage: image)
identação não está na forma correta

2022-11-08 12:25 UTC, LuisNascimento11 commented on WhyNot/WhyNot/PeopleImagesData.swift
> +            AnyView(Text("+\(totalImageNumber - ViewBiulderConstants.maxImages.rawValue)")
identação não está na forma correta

2022-11-08 12:25 UTC, LuisNascimento11 commented on WhyNot/WhyNot/PeopleImagesView.swift
> +    var images: [UIImage]
pularia uma linha aqui

2022-11-09 12:06 UTC, LuisNascimento11 approved these changes
lgtm

2022-11-09 14:40 UTC, LarIsCoding commented on WhyNot/WhyNot/UNO-102/PeopleImagesView.swift
> +            }
Aqui você poderia usar uma função que já retorna as imagens que devem ser mostradas e iterar sobre elas, aí vc só precisa chamar uma função ao invés de duas :)

```suggestion
            ForEach(viewModel.getImagesToShow()) { image in
                PersonImage(image)
            }
```

2022-11-09 14:40 UTC, LarIsCoding commented on WhyNot/WhyNot/UNO-102/PeopleViewModel.swift
> +        }
aqui da pra simplificar
```suggestion
        return images.count > maxImagesNumberPossible
```

2022-11-09 14:43 UTC, Fercomp commented on WhyNot/WhyNot/UNO-102/PeopleViewModel.swift
> +        }
uau

2022-11-10 13:14 UTC, LarIsCoding commented on WhyNot/WhyNot/UNO-102/PeopleViewModel.swift
> +class PeopleVM: ObservableObject {
podia seguir o padrão de nome da view, e chamar PeopleImagesViewModel

```suggestion
class PeopleImagesViewModel: ObservableObject {
```

2022-11-10 13:16 UTC, LarIsCoding commented on WhyNot/WhyNot/UNO-102/PeopleViewModel.swift
> +    @Published var images: [UIImage]
essa galerinha num precisa ser published, já que essas variáveis não são acessadas pela view
```suggestion
    let maxImagesNumberPossible = 4
    let images: [UIImage]
```

2022-11-10 13:20 UTC, LarIsCoding approved these changes

2022-11-11 11:14 UTC, merged