Feature/uno 72
UNO-Academy/UNO pull request #20
Opened 2022-11-16 12:22 UTC by LuisNascimento11

# Review Feature 72

## Objetivo

Implementar o componente de card das experiências

## Features Implementadas

- Card das experiências
- Correção do Pod para implementar testes

## Melhorias

- Refatoração de alguns códigos

## Comparação do resultado obtido

Ficou levemente diferente do que estava proposto no Figma, pois tive que colocar um aspect ratio diferente, já que quando coloquei igual ao do figma, quebrava o texto dentro das tags

### Figma

<img width="371" alt="Screen Shot 2022-11-16 at 09 19 18" src="https://user-images.githubusercontent.com/31076284/202179114-e66ede68-b3f7-4867-8421-cafee98b0d66.png">

### Código

<img width="394" alt="Screen Shot 2022-11-16 at 09 14 11" src="https://user-images.githubusercontent.com/31076284/202179285-099ae713-553c-4c5f-9ce3-a531598ebb21.png">

2022-11-17 14:09 UTC, Bassani-Paulo commented on WhyNot/WhyNot/Components/Tag/TagData.swift
> +        default:
eu não acho q esse seja o uso correto do "default" pra mim faz um case 3 e o default é retorna um erro

2022-11-17 14:43 UTC, Bassani-Paulo reviewed
Tem apenas um comentário, as partes que eu sei que são da Lari/Will eu não comentei nada pq já foram comentadas no outro PR.

2022-11-17 14:44 UTC, LarIsCoding commented on WhyNot/WhyNot/Scenes/Experiences/ExperiencesView.swift
> +struct Teste: Identifiable {
batata, pode apagar o conteúdo desse arquivo por favor?

não precisa apagar o arquivo, só o conteúdo

2022-11-17 14:45 UTC, LarIsCoding commented on WhyNot/WhyNot/Scenes/Experiences/ExperiencesViewModel.swift
> +class ExperiencesViewModel: ObservableObject {
mesma coisa, apagar o conteudo desse arquivo

2022-11-17 14:46 UTC, LarIsCoding commented on WhyNot/WhyNot/data/repository/ExperienceRepository.swift
> +    let toDoExperiences: [Experience]
esse qrquivo também

2022-11-17 14:49 UTC, LarIsCoding commented
olhando os prints que vc colocou, me parece que o espaçamento entre o conteúdo do card e a borda do cardo (tanto horizontais quanto verticais) então diferentes do figma

já o tamanho do ícone da tag parece maior também

2022-11-17 14:59 UTC, LarIsCoding commented on WhyNot/WhyNot/Components/Tag/TagData.swift
>  enum TagValue: String {
ce pode aproveitar e colocar isso no localizable?

eu ia colocar, mas vai acabar dando conflito com o seu pr

2022-11-17 17:30 UTC, Bassani-Paulo commented on WhyNot/WhyNot/Components/Tag/TagData.swift
>  enum TagValue: String {
eu posso fazer na minha branch se quiserem. assim q o batata resolver seus comentários já da pra eu puxar as mudanças dele e fazer meu PR

2022-11-17 17:34 UTC, LuisNascimento11 commented on WhyNot/WhyNot/Scenes/Experiences/ExperiencesView.swift
> +struct Teste: Identifiable {
beleza

2022-11-17 17:35 UTC, LuisNascimento11 commented on WhyNot/WhyNot/Components/Tag/TagData.swift
> +        default:
então, eu deixei do jeito que o fer tinha feito, só mudei para funções específicas

2022-11-18 11:57 UTC, LuisNascimento11 commented
> olhando os prints que vc colocou, me parece que o espaçamento entre o conteúdo do card e a borda do cardo (tanto horizontais quanto verticais) então diferentes do figma
> 
> já o tamanho do ícone da tag parece maior também

Alterei

![Screen Shot 2022-11-18 at 08 55 54](https://user-images.githubusercontent.com/31076284/202699989-fdf577a4-ef1c-4be2-ace4-7a1e697ea500.png)

2022-11-18 14:49 UTC, Bassani-Paulo approved these changes

2022-11-20 21:18 UTC, LarIsCoding commented on WhyNot/WhyNot/TabBar.swift
> +            // ExperiencesView()
por que isso está comentado?

2022-11-20 21:19 UTC, LarIsCoding commented on WhyNot/WhyNot/Scenes/Experiences/ExperiencesView.swift
> -struct ExperiencesView: View {
por que apagou esse arquivo?

2022-11-21 12:09 UTC, Fercomp commented on WhyNot/WhyNot/data/remoteDatabase/API/ExperienceAPI.swift
> +        let teste = try await crudService.readDocumentsFilteredBy(
É pra ser um teste mesmo ?

2022-11-21 14:36 UTC, luizgustavo09 commented on WhyNot/WhyNot/Components/CardView/CardView.swift
> +                    UIImage(named: "adventure")!
Não é melhor colocar uma imagem default no lugar desse force unwrappée

2022-11-21 14:40 UTC, luizgustavo09 commented on WhyNot/WhyNot/Scenes/Experiences/ExperiencesView.swift
> -struct ExperiencesView: View {
também não entendi

2022-11-21 14:42 UTC, luizgustavo09 approved these changes
Por mim tá ok, só os mesmos comentários da lari que eu n entendi.

2022-11-21 14:42 UTC, luizgustavo09 requested changes
arruma os conflitos que eu aprovo

2022-11-22 11:25 UTC, LuisNascimento11 commented on WhyNot/WhyNot/Scenes/Experiences/ExperiencesView.swift
> -struct ExperiencesView: View {
apaguei o texto só

2022-11-22 11:35 UTC, luizgustavo09 approved these changes
LGTM!

2022-11-22 11:39 UTC, merged