Feature/uno 73
UNO-Academy/UNO pull request #21
Opened 2022-11-16 12:53 UTC by luizgustavo09

Implementei a query que devolve os amigos interessados em uma experiência

2022-11-17 11:52 UTC, LuisNascimento11 approved these changes
lgtm

2022-11-17 11:52 UTC, LuisNascimento11 commented on WhyNot/WhyNot/Scenes/Experiences/ExperiencesView.swift
> +struct Teste: Identifiable {
Essa struct vai continuar sendo usada? Se for mudaria o nome

2022-11-17 12:43 UTC, Bassani-Paulo reviewed
fiz alguns comentários, verifica quais se relacionam com vc. eu mandei uma cópia dos comentários pra lari pra caso tenha sido algo q ela q mexeu

2022-11-17 12:43 UTC, Bassani-Paulo commented on WhyNot/WhyNot/Components/Tag/TagData.swift
>  enum TagValue: String {
não precisa mudar aqui, é só usar isso como key na hora de por no text/label

2022-11-17 12:43 UTC, Bassani-Paulo commented on WhyNot/WhyNot/Scenes/Experiences/ExperiencesViewModel.swift
> +    func getDaysLeft() -> Int? {
talvez fazer throwable ao invés de retornar opitional

2022-11-17 12:43 UTC, Bassani-Paulo commented on WhyNot/WhyNot/data/model/Experience.swift
> +    let effort: Int
aqui o tipo n poderia ser enum ao invés de Int? Sendo int, oq acontece se alguém entrar o número 7 sem querer? Quando é enum não tem como acontecer isso

2022-11-17 12:43 UTC, Bassani-Paulo commented on WhyNot/WhyNot/data/remoteDatabase/API/UserAPI.swift
> +    func isLogged() -> Bool {
isso daqui é temporario? talvez seja válido colocar um TODO pra verificar direito se está logado no futuro

2022-11-17 12:55 UTC, LarIsCoding commented on WhyNot/WhyNot/Components/Tag/TagData.swift
>  enum TagValue: String {
mas precisa colocar no localizable

2022-11-17 12:56 UTC, LarIsCoding commented on WhyNot/WhyNot/Scenes/Experiences/ExperiencesView.swift
> +struct Teste: Identifiable {
vai não

will, se não foi muito trampo vc poderia deixar esse arquivo em branco?

não precisa apagar o arquivo, só o conteúdo dele

2022-11-17 12:56 UTC, LarIsCoding commented on WhyNot/WhyNot/Scenes/Experiences/ExperiencesViewModel.swift
> +    func getDaysLeft() -> Int? {
mesma coisa pra esse arquivo, deixa em branco pf

2022-11-17 12:59 UTC, LarIsCoding commented on WhyNot/WhyNot/data/model/Experience.swift
> +    let effort: Int
não dá pra ser enum porque essa estrutura é exatamente o que volta do banco de dados, e no banco não existe Enums, só tipos normais

mas tem algumas melhorias que quero fazer no futuro pra ter objetos de banco e objetos de domínio

2022-11-17 13:01 UTC, LarIsCoding commented on WhyNot/WhyNot/data/remoteDatabase/API/UserAPI.swift
> +    func isLogged() -> Bool {
will, pode apagar as funções isLogged() e getLoggedUser()?

2022-11-17 13:02 UTC, LarIsCoding commented on WhyNot/WhyNot/data/remoteDatabase/API/ExperienceAPI.swift
> +        let teste = try await crudService.readDocumentsFilteredBy(
se puder tirar esse teste e fazer um return try await, ficaria mais clean

2022-11-17 13:06 UTC, LarIsCoding commented on WhyNot/WhyNot/data/repository/ExperienceRepository.swift
> +import FirebaseFirestore
Poderia deixar esse arquivo em brando tbm?

2022-11-17 13:07 UTC, LarIsCoding commented on WhyNot/WhyNot/data/remoteDatabase/API/UserAPI.swift
> +        let data = try await collectionReference.document(userID).getDocument()
aqui, ao invés de data, poderia ser userData, já que diversos dados são usados nessa funçao, ou até mesmo userDocument

2022-11-17 13:09 UTC, LarIsCoding commented on WhyNot/WhyNot/data/remoteDatabase/CRUDServices.swift
> +                if data.contains(experienceID) {
aqui, ao invés de data, poderia ser interestExperiencesList

2022-11-17 13:10 UTC, LarIsCoding requested changes
tá top, só queria que tu tirasse as partes de código que eu apontei que eu que fiz pra nao deixar o PR muito confuso

2022-11-17 13:12 UTC, Bassani-Paulo commented on WhyNot/WhyNot/Components/Tag/TagData.swift
>  enum TagValue: String {
sim, se tiver algo q vcs não saibam traduzir (ou caso n saiba mexer com localizable), pode mandar uma mensagem pra mim q eu insiro

2022-11-17 13:13 UTC, Bassani-Paulo commented on WhyNot/WhyNot/data/model/Experience.swift
> +    let effort: Int
blz

2022-11-17 16:31 UTC, luizgustavo09 commented on WhyNot/WhyNot/Scenes/Experiences/ExperiencesView.swift
> +struct Teste: Identifiable {
resolvido!

2022-11-17 16:33 UTC, luizgustavo09 commented on WhyNot/WhyNot/data/model/Experience.swift
> +    let effort: Int
acho que seria zuado de guardar no banco o enum, a responsabilidade de não inserir valores fora do range vai acabar sendo responsabilidade nossa mesmo

2022-11-17 16:33 UTC, luizgustavo09 commented on WhyNot/WhyNot/data/remoteDatabase/API/UserAPI.swift
> +    func isLogged() -> Bool {
posso

2022-11-20 21:22 UTC, LarIsCoding approved these changes
lgtm

2022-11-20 21:23 UTC, LarIsCoding commented on WhyNot/WhyNot/Scenes/Experiences/ExperiencesView.swift
> -struct ExperiencesView: View {
esse arquivo não precisa apagar

2022-11-20 21:24 UTC, LarIsCoding commented on WhyNot/WhyNot/Scenes/Experiences/ExperiencesView.swift
> -struct ExperiencesView: View {
esse arquivo não precisava apagar, mas acho que tudo bem mergear assim

2022-11-21 11:52 UTC, merged