Feature/uno 117 new
UNO-Academy/UNO pull request #30
Opened 2022-11-29 01:25 UTC by Fercomp

Com a ajuda divina, finalmente estou fazendo esse pr

2022-11-29 11:22 UTC, luizgustavo09 commented on WhyNot/WhyNot/Domain/Model/User.swift
> +struct User: Codable, Hashable {
pq q teve que passar pra hashable mesmo?

2022-11-29 11:24 UTC, luizgustavo09 commented on WhyNot/WhyNot/Presentation/Components/Friends/FriendCardView.swift
> +                Button(action: {
não quer dar uma quebra de linha aqui no Action? Daí fica um parâmetro por linha

2022-11-29 11:27 UTC, luizgustavo09 commented on WhyNot/WhyNot/Presentation/Components/Friends/FriendCardViewModel.swift
> +        action: @escaping () -> Void = {}
Pq essa action tá vazia por padrão? A gente vai deixar chamar o construtor sem passar a Action?

2022-11-29 11:28 UTC, luizgustavo09 commented on WhyNot/WhyNot/Presentation/Components/Friends/FriendCardViewModel.swift
> +    static func == (lhs: FriendCardViewModel, rhs: FriendCardViewModel) -> Bool {
o que seria lhs e rhs?

2022-11-29 11:29 UTC, luizgustavo09 commented on WhyNot/WhyNot/Presentation/Components/Friends/FriendCardViewModel.swift
> +            return UIImage(data: image)!
Sugiro tirar esse force e colocar objeto de UIImage vazio ou então criar uma image default para todos esses casos que falham

2022-11-29 11:29 UTC, luizgustavo09 commented on WhyNot/WhyNot/Presentation/Components/Friends/FriendCardViewModel.swift
> +            return UIImage(systemName: "person.crop.circle")!
o mesmo vale aqui

2022-11-29 11:32 UTC, luizgustavo09 requested changes
Tirando esses detalhes que pontuei tá ok para mim mas só vou liberar quando arrumar os force

2022-11-30 13:33 UTC, Bassani-Paulo commented on WhyNot/WhyNot/Presentation/Components/Friends/FriendCardViewModel.swift
> +    static func == (lhs: FriendCardViewModel, rhs: FriendCardViewModel) -> Bool {
também não entendi. onde essa função é usada?

2022-12-01 12:06 UTC, Fercomp commented on WhyNot/WhyNot/Presentation/Components/Friends/FriendCardViewModel.swift
> +        action: @escaping () -> Void = {}
Sim, tem vezes que não irá ter botão, logo não tera ação

2022-12-01 12:07 UTC, Fercomp commented on WhyNot/WhyNot/Presentation/Components/Friends/FriendCardViewModel.swift
> +    static func == (lhs: FriendCardViewModel, rhs: FriendCardViewModel) -> Bool {
É pra quando e tiver duas Friends card view model e quiser ver se elas são iguais, eu coloquei pra só olhar o id das dos, o lhs seria o viewmodel do lado esquerdo e rhs o direito

2022-12-01 12:14 UTC, luizgustavo09 commented on WhyNot/WhyNot/Presentation/Components/Friends/FriendCardViewModel.swift
> +        action: @escaping () -> Void = {}
não é melhor fazer ela um opcional?

2022-12-01 12:31 UTC, Fercomp commented on WhyNot/WhyNot/Domain/Model/User.swift
> +struct User: Codable, Hashable {
Estou um usando um for each, com users, para isso precisa ser hwshable

2022-12-01 12:57 UTC, LarIsCoding commented on WhyNot/WhyNot/Presentation/Components/Friends/FriendCardViewModel.swift
> +        action()
fazer um switch aqui com TODO de functions

2022-12-01 13:28 UTC, LarIsCoding commented on WhyNot/WhyNot/Presentation/Components/Friends/FriendsCollection.swift
> +struct FriendsCollectionView: View {
UserListView

2022-12-01 13:31 UTC, LarIsCoding commented on WhyNot/WhyNot/Presentation/Components/Friends/FriendsCollection.swift
> +                FriendCardView(viewModel: FriendCardViewModel(user: friend))
UserListItemView

2022-12-01 13:31 UTC, LarIsCoding commented on WhyNot/WhyNot/Presentation/Components/Friends/FriendsCollection.swift
> +struct Vider: PreviewProvider {
faltou o título completo eheh

2022-12-01 14:26 UTC, LarIsCoding approved these changes

2022-12-01 14:27 UTC, luizgustavo09 approved these changes

2022-12-01 14:28 UTC, merged